---
- name: snmp ro/rw string configuration
  hosts: routers
  gather_facts: no

  tasks:

    - name: ensure that the desired snmp strings are present
      ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW
         
    - name: validate snmp
      ios_command:
        commands:
         - sho run | i snmp
      register: snmp

    - name: print out the results of ios_facts
      debug:
        msg: "{{ snmp }}"
